services:
  mysql:
    image: mysql:latest
    container_name: outcome
    ports:
      - "3306:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: outcome
      MYSQL_USER: iri
      MYSQL_PASSWORD: 1234qwer

  spring-boot-app:
    image: outcomespring:1.0
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/outcome
      SPRING_DATASOURCE_USERNAME: iri
      SPRING_DATASOURCE_PASSWORD: 1234qwer

  web:
    container_name: web
    image: iri051/web-nginx
    expose:
#      - 8080
      - 80
#    ports:
#      - 8080:8080

  nginx:
    container_name: nginx
    image: iri051/web-nginx
    ports:
      - 80:80
    depends_on:
      # 추가함
      - spring-boot-app
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf