networks:
  mynetwork:
    driver: bridge

services:
  mysql-master:
    image: mysql:8.0.38
    container_name: mysql-master
    ports:
      - "3306:3306" # 호스트의 3306 포트를 컨테이너의 3306 포트에 매핑
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: outcome
      MYSQL_USER: iri
      MYSQL_PASSWORD: 1234qwer
      MYSQL_MAX_CONNECTIONS: 500
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/config:/etc/mysql/conf.d
    networks:
      - mynetwork

  mysql-slave:
    image: mysql:8.0.38
    container_name: mysql-slave
    ports:
      - "3307:3306" # 호스트의 3307 포트를 컨테이너의 3306 포트에 매핑
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: outcome
      MYSQL_USER: iri
      MYSQL_PASSWORD: 1234qwer
      MYSQL_MAX_CONNECTIONS: 500
    depends_on:
      - mysql-master
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/config:/etc/mysql/conf.d
    networks:
      - mynetwork


  spring-outcome:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-outcome
    ports:
      - "8080:8080"
    depends_on:
      - mysql-master
    environment:
      SPRING_DATASOURCE_WRITE_URL: jdbc:mysql://mysql-master:3306/outcome
      SPRING_DATASOURCE_WRITE_USERNAME: iri
      SPRING_DATASOURCE_WRITE_PASSWORD: 1234qwer
      SPRING_DATASOURCE_READ_URL: jdbc:mysql://mysql-slave:3306/outcome
      SPRING_DATASOURCE_READ_USERNAME: iri
      SPRING_DATASOURCE_READ_PASSWORD: 1234qwer
    networks:
      - mynetwork


#    volumes:
#      - ./Outcome-0.0.1-SNAPSHOT.jar:/app/app.jar
#    working_dir: /app
#    command: [ "java", "-jar", "app.jar" ]
  outcomebatch:
    build:
      context: ../OutcomeBatch
      dockerfile: Dockerfile
    container_name: OutcomeBatch
    ports:
      - "8081:8080"
    depends_on:
      - mysql-master
      - mysql-slave
    environment:
      SPRING_DATASOURCE_BATCH_URL: jdbc:mysql://mysql-master:3306/outcome
      SPRING_DATASOURCE_BATCH_USERNAME: iri
      SPRING_DATASOURCE_BATCH_PASSWORD: 1234qwer
      SPRING_DATASOURCE_STREAMING_URL: jdbc:mysql://mysql-slave:3306/outcome
      SPRING_DATASOURCE_STREAMING_USERNAME: iri
      SPRING_DATASOURCE_STREAMING_PASSWORD: 1234qwer

    networks:
      - mynetwork

  web:
    container_name: web
    image: nginx
    expose:
      - 80
    networks:
      - mynetwork
#      - 8080
#    ports:
#      - 8080:8080

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    depends_on:
      # 추가함
      - spring-outcome
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork